export const environment = {
  production: true,
  clientId: '87ac444283e74b2caa2a9be4134a8d67',
  clientSecret: '0b8b21dbb9d84255ad0c94681ae3d56e',
  redirectUri: 'http://localhost:4200/callback',
  apiConfig: 'https://api.spotify.com/v1',
  scope:
    'ugc-image-upload streaming user-read-private user-read-email user-modify-playback-state user-read-currently-playing user-library-read playlist-modify-public playlist-modify-private user-top-read user-read-playback-state',
  state: '123',
  apiPaths: {
    mePlaylist: '/me/playlists ',
    picturePlaylist: (id: string) => `/playlists/${id}/images`,
    infoPlaylist: (id: string) => `/playlists/${id}`,
    getPlaylist: (id: string) => `/playlists/${id}/tracks`,
    topTrack: `/browse/featured-playlists`,
    getArtist: (id: string) => `/artists/${id}`,
    getTrackAlbum: (id: string) => `/albums/${id}/tracks`,
    getAlbumDetail: (id: string) => `/albums/${id}`,
    getNewAlbum: '/browse/new-releases',
    playMusic: '/me/player/play',
    pauseMusic: '/me/player/pause',
    currentPlay: '/me/player/currently-playing',
    getTrack: (id: string) => `/tracks/${id}`,
    getTrackArtist: (id: string) => `/artists/${id}/top-tracks`,
    getDevice: '/me/player/devices',
    search: (input: string, type: string) => `/search?q=${input}&type=${type}`,
    next: (deviceId: string) => `/me/player/next?${deviceId}`,
    previous: (deviceId: string) => `/me/player/previous?${deviceId}`,
    seek: '/me/player/seek',
    getTrackPlaylist: (id: string) => `/playlists/${id}/tracks`,
    createNewPlaylist: (id: string) => `/users/${id}/playlists`,
    deletePlaylist: (id: string) => `/playlists/${id}/followers`,
    updateImgPlaylist: (id: string) => `/playlists/${id}/images`,
    updatePlaylistDetail: (id: string) => `/playlists/${id}`,
  },
};
